/**
 * Implemented Atlas surfaces traced to the Phase 2 Payroll Project Plan.
 *
 * Planned-only rows are deliberately excluded. Keep this as the single source
 * used by the Company Rules > Modules & Features register.
 */
export const moduleFeatureCatalog = [
  {
    id: 'company-profile',
    area: 'Company setup',
    name: 'Company information & payroll profile',
    description: 'Maintain the company identity, payroll contacts, banking and authorized representatives used by payroll.',
    location: 'Company Configuration / Company Information',
    target: 'view:information',
    features: [
      { name: 'Contact and payroll information', refs: ['HTP013', 'HTP014'] },
      { name: 'Payment modes and company bank accounts', refs: ['HTP015'] },
      { name: 'Authorized contact persons', refs: ['HTP016', 'HTP099', 'HTP100'] },
      { name: 'Authorized signatories and e-signatures', refs: ['HTP017', 'HTP095', 'HTP096'] },
      { name: 'Company information export', refs: ['HTP072'] },
    ],
  },
  {
    id: 'basic-pay',
    area: 'Payroll configuration',
    name: 'Basic pay & pay rates',
    description: 'Configure effective-dated pay types, factor days, working hours, minimum wage and ECOLA eligibility.',
    location: 'Services Information / Basic Pay & Pay Rates',
    target: 'view:service:basicPay',
    features: [
      { name: 'Regional minimum wage setup', refs: ['HTP020'] },
      { name: 'Effective-dated pay rates and multiple rate types', refs: ['HTP047'] },
      { name: 'Factor days and working hours', refs: ['HTP048'] },
    ],
  },
  {
    id: 'earnings',
    area: 'Payroll configuration',
    name: 'Earnings, allowances & bonuses',
    description: 'Maintain pay items with employee assignment, tax treatment, frequency, computation basis and GL mapping.',
    location: 'Services Information / Earnings, Variable Allowances and Bonuses',
    target: 'view:service:earnings',
    features: [
      { name: 'Earning setup and employee-group assignment', refs: ['HTP038'] },
      { name: 'Recurring income frequency', refs: ['HTP040'] },
      { name: 'Timekeeping-based variable allowances', refs: ['HTP041'] },
      { name: 'Bonus basis, schedule and taxability', refs: ['HTP042'] },
    ],
  },
  {
    id: 'deductions-loans',
    area: 'Payroll configuration',
    name: 'Deductions & loans',
    description: 'Configure deductions and company/government loans with balances, collection schedules and take-home-pay priority.',
    location: 'Services Information / Deductions and Loans',
    target: 'view:service:deductions',
    features: [
      { name: 'Deduction basis, schedule and GL setup', refs: ['HTP043'] },
      { name: 'Company loan terms and amortization', refs: ['HTP044'] },
      { name: 'SSS and HDMF government loans', refs: ['HTP045'] },
      { name: 'Deduction and loan hierarchy', refs: ['HTP046'] },
      { name: 'Withholding and statutory deduction tagging', refs: ['HTP160'] },
    ],
  },
  {
    id: 'time-attendance',
    area: 'Payroll configuration',
    name: 'Time & attendance controls',
    description: 'Maintain work hours, breaks, shifts, core hours, flexible-time rules and payroll rounding behavior.',
    location: 'Services Information / Time & Attendance',
    target: 'view:service:timeAttendance',
    features: [
      { name: 'Shift and work-schedule data used by payroll', refs: ['HTP145'] },
      { name: 'Timekeeping import into payroll processing', refs: ['HTP280'] },
    ],
  },
  {
    id: 'leave-benefits',
    area: 'Payroll configuration',
    name: 'Benefits & leave',
    description: 'Configure leave eligibility, accrual, carryover, forfeiture, conversion and payroll treatment.',
    location: 'Services Information / Benefits & Leave',
    target: 'view:service:leaveBenefits',
    features: [
      { name: 'Leave pay-item setup', refs: ['HTP037'] },
      { name: 'Leave ledger, accrual, adjustment and forfeiture', refs: ['HTP108', 'HTP109', 'HTP131', 'HTP132'] },
      { name: 'Leave conversion', refs: ['HTP111', 'HTP134'] },
    ],
  },
  {
    id: 'overtime',
    area: 'Payroll configuration',
    name: 'Overtime configuration',
    description: 'Maintain day-type rates, effective periods, eligibility conditions and approval requirements.',
    location: 'Settings / Overtime Configuration',
    target: 'screen:settings-workspace:overtime',
    features: [
      { name: 'Overtime types, rates and tables', refs: ['HTP024'] },
    ],
  },
  {
    id: 'computational-basis',
    area: 'Payroll configuration',
    name: 'Computational basis & policy engines',
    description: 'Govern approved formulas, reusable policy codes, company-specific values and statutory/reference dependencies.',
    location: 'Services Information / Computational Basis',
    target: 'view:computations',
    features: [
      { name: 'View, edit and export approved computations', refs: ['HTP018', 'HTP019', 'HTP073', 'HTP074', 'HTP075'] },
      { name: 'Take-home pay, retirement and final-pay policy codes', refs: ['HTP053', 'HTP054', 'HTP055', 'HTP079'] },
      { name: 'Gross-up and taxable-ceiling computations', refs: ['HTP050', 'HTP051', 'HTP052'] },
      { name: 'Provident, pension and maternity computations', refs: ['HTP076', 'HTP077', 'HTP078', 'HTP080'] },
      { name: 'Annual tax forecast and projection', refs: ['HTP081', 'HTP082'] },
    ],
  },
  {
    id: 'reference-tables',
    area: 'Payroll configuration',
    name: 'Reference tables',
    description: 'Maintain versioned payroll reference values and feed controlled dropdowns across company, employee and payroll modules.',
    location: 'Settings / Reference Table',
    target: 'screen:reference-settings',
    features: [
      { name: 'Reference-table setup and governed linkages', refs: ['HTP023'] },
      { name: 'View, edit, upload and export versions', refs: ['HTP062', 'HTP063', 'HTP097', 'HTP098'] },
      { name: 'De Minimis ceilings as effective reference data', refs: ['HTP051', 'HTP184'] },
    ],
  },
  {
    id: 'calendar',
    area: 'Payroll configuration',
    name: 'Payroll calendar & timelines',
    description: 'Control payouts, payroll locking, statutory deadlines, holidays, billing cutoffs and notification timing.',
    location: 'Settings / Payroll Calendar',
    target: 'screen:settings-workspace:calendar',
    features: [
      { name: 'Payout calendar and approval levels', refs: ['HTP028'] },
      { name: 'Payroll process timelines and reminders', refs: ['HTP029'] },
      { name: 'Statutory deadlines', refs: ['HTP031'] },
      { name: 'Holiday calendar', refs: ['HTP032'] },
      { name: 'Billing cutoffs linked to billing', refs: ['HTP033'] },
      { name: 'Calendar view, edit, upload and export', refs: ['HTP085', 'HTP086', 'HTP087'] },
    ],
  },
  {
    id: 'pay-codes',
    area: 'Payroll configuration',
    name: 'Pay codes & GL mapping',
    description: 'Maintain payroll code classifications, taxability and accounting mappings used by transactions and journals.',
    location: 'Settings / Pay Code',
    target: 'screen:settings-workspace:payCodes',
    features: [
      { name: 'Pay-code library and payroll classifications', refs: ['HTP038', 'HTP042', 'HTP043'] },
      { name: 'General-ledger mapping and segmented output', refs: ['HTP226', 'HTP328'] },
    ],
  },
  {
    id: 'employee-masterfile',
    area: 'Employee data',
    name: 'Employee masterfile payroll records',
    description: 'Maintain effective-dated employee payroll, tax, loan, earning, deduction, currency, YTD and allocation records.',
    location: 'Core / Employee Masterfile',
    target: 'screen:employee',
    features: [
      { name: 'Tax and previous-employer information', refs: ['HTP105', 'HTP107', 'HTP128'] },
      { name: 'Employee loan profile', refs: ['HTP110', 'HTP133'] },
      { name: 'Payroll records and pay history', refs: ['HTP116', 'HTP139'] },
      { name: 'Fixed earnings, bonuses and deductions', refs: ['HTP117', 'HTP118', 'HTP119', 'HTP140', 'HTP141', 'HTP142'] },
      { name: 'Multi-currency history', refs: ['HTP120', 'HTP143'] },
      { name: 'YTD and previous-employer balances', refs: ['HTP123', 'HTP124'] },
      { name: 'Cost centers and 100% allocation control', refs: ['HTP114', 'HTP137', 'HTP310'] },
    ],
  },
  {
    id: 'payroll-transactions',
    area: 'Payroll operations',
    name: 'Payroll transactions',
    description: 'Create, calculate, review, post, lock, cancel and export regular, selective, special and multi-currency payroll runs.',
    location: 'Payroll / Payroll Processing',
    target: 'screen:payroll-workspace:transactions',
    features: [
      { name: 'Create, edit, view and export payroll runs', refs: ['HTP148', 'HTP149', 'HTP150', 'HTP151'] },
      { name: 'Single, selective and all-employee processing', refs: ['HTP152'] },
      { name: 'Special-payroll field overrides', refs: ['HTP153'] },
      { name: 'Posting, retention, recalculation and locking', refs: ['HTP154', 'HTP155', 'HTP322'] },
      { name: 'Multi-currency payroll lifecycle', refs: ['HTP156', 'HTP157', 'HTP158', 'HTP159'] },
    ],
  },
  {
    id: 'payslip',
    area: 'Payroll operations',
    name: 'Payslip designer',
    description: 'Create branded templates, choose visible fields, retain YTD values and designate one active format.',
    location: 'Payroll / Payslip Designer',
    target: 'screen:payroll-workspace:payslip',
    features: [
      { name: 'Standard and custom payslip templates', refs: ['HTP059'] },
    ],
  },
  {
    id: 'statutory-tables',
    area: 'Payroll operations',
    name: 'Statutory tables',
    description: 'Maintain effective versions of withholding, SSS, PhilHealth, HDMF and De Minimis data, with used versions locked.',
    location: 'Settings / Statutory Table',
    target: 'screen:statutory-settings',
    features: [
      { name: 'Withholding-tax tables', refs: ['HTP180'] },
      { name: 'PhilHealth contribution tables', refs: ['HTP181'] },
      { name: 'SSS contribution tables', refs: ['HTP182'] },
      { name: 'HDMF contribution tables', refs: ['HTP183'] },
      { name: 'De Minimis tables', refs: ['HTP184'] },
    ],
  },
  {
    id: 'remittance',
    area: 'Payroll operations',
    name: 'Remittance monitoring',
    description: 'Track government receipts against posted payouts with agency, filing, payment and posting details.',
    location: 'Payroll / Remittance Monitoring',
    target: 'screen:payroll-workspace:remittance',
    features: [
      { name: 'Company remittance setup', refs: ['HTP021'] },
      { name: 'Create, edit, upload, view and export remittances', refs: ['HTP088', 'HTP089', 'HTP090', 'HTP091'] },
    ],
  },
  {
    id: 'billing',
    area: 'Payroll operations',
    name: 'Billing configuration & transactions',
    description: 'Configure billing bases and cutoffs, then move generated transactions through preparer, checker and reviewer stages.',
    location: 'Payroll / Billing',
    target: 'screen:payroll-workspace:billing',
    features: [
      { name: 'Straight, headcount, bracket, percentage and custom billing setup', refs: ['HTP022'] },
      { name: 'Billing cutoff calendar', refs: ['HTP033'] },
      { name: 'Edit, view and export billing transactions', refs: ['HTP092', 'HTP093', 'HTP094'] },
    ],
  },
  {
    id: 'journal',
    area: 'Payroll operations',
    name: 'Journal entries',
    description: 'Review payroll accounting output and enforce balanced debit and credit totals before posting.',
    location: 'Payroll / Journal Entry',
    target: 'screen:payroll-workspace:journal',
    features: [
      { name: 'Balanced payroll journal output', refs: ['HTP226'] },
    ],
  },
  {
    id: 'reports',
    area: 'Payroll operations',
    name: 'Payroll reports',
    description: 'Generate governed, permission-aware payroll, employee and audit artifacts with parameters and run history.',
    location: 'Core / Reports',
    target: 'screen:reports',
    features: [
      { name: 'Employee masterfile report', refs: ['HTP186'] },
      { name: 'Payroll and accounting report artifacts', refs: ['HTP226'] },
      { name: 'PDF, Excel and CSV output', refs: ['HTP306'] },
    ],
  },
  {
    id: 'access-approvals',
    area: 'Governance & support',
    name: 'Access rights & approvals',
    description: 'Control role grants, separation of duties and multi-level approval groups for governed payroll actions.',
    location: 'Settings / Access & Approvals',
    target: 'screen:settings-workspace:accessRights',
    features: [
      { name: 'Per-employee approval groups', refs: ['HTP284'] },
      { name: 'Role-based interface access', refs: ['HTP327'] },
    ],
  },
  {
    id: 'security',
    area: 'Governance & support',
    name: 'Security configuration',
    description: 'Manage session and sign-in controls, SSO enforcement and soft user-account deactivation/reactivation.',
    location: 'Settings / Security Configuration',
    target: 'screen:settings-workspace:security',
    features: [
      { name: 'Block/unblock and SSO enablement', refs: ['HTP307'] },
      { name: 'Soft deactivation and reactivation', refs: ['HTP308'] },
    ],
  },
  {
    id: 'notifications',
    area: 'Governance & support',
    name: 'Notifications',
    description: 'Route calendar, approval, ticket, onboarding and report events through shared, auditable notification rules.',
    location: 'Company Configuration / Notifications',
    target: 'view:workspace:notifications',
    features: [
      { name: 'Calendar and payroll deadline reminders', refs: ['HTP029', 'HTP269'] },
    ],
  },
  {
    id: 'ticketing',
    area: 'Governance & support',
    name: 'Ticketing & helpdesk',
    description: 'Capture support requests and govern topic routing, destinations and service-level targets.',
    location: 'Core / Tickets',
    target: 'screen:ticketing',
    features: [
      { name: 'Ticketing, helpdesk and reporting', refs: ['HTP277'] },
    ],
  },
  {
    id: 'audit-log',
    area: 'Governance & support',
    name: 'Audit log',
    description: 'Review append-only company, configuration, payroll and reporting events emitted by implemented modules.',
    location: 'Settings / Audit Log',
    target: 'screen:settings-workspace:audit',
    features: [
      { name: 'Sign-in, sign-out and chronological add/edit/delete history', refs: ['All features 64-69'] },
    ],
  },
];

export const moduleFeatureAreas = ['All modules', ...new Set(moduleFeatureCatalog.map(module => module.area))];
